version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
      - ~/.ssh:/root/.ssh:ro
    working_dir: /workspace
    environment:
      - PYTHONPATH=/workspace
    ports:
      - "8888:8888"  # Jupyter
      - "8000:8000"  # Docs server
    command: bash
    stdin_open: true
    tty: true

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - PYTHONPATH=/workspace
    command: pytest -v

  docs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
      - ./docs/_build:/workspace/docs/_build
    working_dir: /workspace
    ports:
      - "8000:8000"
    command: >
      bash -c "cd docs && 
               make html && 
               cd _build/html && 
               python -m http.server 8000 --bind 0.0.0.0"

  spice-sim:
    build:
      context: .
      dockerfile: Dockerfile.spice
    volumes:
      - .:/workspace
      - ./temp:/workspace/temp
    working_dir: /workspace
    environment:
      - SPICE_SIMULATOR=ngspice
    command: bash