# Prometheus configuration for Analog PDE Solver monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'analog-pde-solver'
    environment: 'production'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/*.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Analog PDE Solver application metrics
  - job_name: 'analog-pde-solver'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['analog-pde-solver:8000']
    scrape_timeout: 5s
    honor_labels: true

  # SPICE simulation metrics
  - job_name: 'spice-simulator'
    scrape_interval: 30s
    metrics_path: '/spice/metrics'
    static_configs:
      - targets: ['spice-sim:9091']
    scrape_timeout: 10s

  # Hardware testing metrics
  - job_name: 'hardware-tests'
    scrape_interval: 60s
    metrics_path: '/hardware/metrics'
    static_configs:
      - targets: ['hardware:9092']
    scrape_timeout: 15s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']

  # Docker container metrics
  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']

  # Redis metrics (if using Redis for caching)
  - job_name: 'redis'
    scrape_interval: 15s
    static_configs:
      - targets: ['redis-exporter:9121']

  # Application performance monitoring
  - job_name: 'performance-tests'
    scrape_interval: 300s  # 5 minutes
    metrics_path: '/perf/metrics'
    static_configs:
      - targets: ['perf-monitor:9093']
    scrape_timeout: 30s

# Remote write configuration (for long-term storage)
remote_write:
  - url: "http://thanos-receive:19291/api/v1/receive"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500