name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC, 0BSD
          deny-licenses: GPL-2.0, GPL-3.0, LGPL-2.0, LGPL-2.1, LGPL-3.0
          
      - name: 'License Compliance Check'
        run: |
          echo "Checking license compliance..."
          pip install pip-licenses
          pip-licenses --format=json --output-file=license-report.json
          
      - name: 'Upload License Report'
        uses: actions/upload-artifact@v3
        with:
          name: license-compliance-report
          path: license-report.json